language: node_js

node_js:
  - node

jobs:
  include:
    - stage: release
      node_js: node
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run build && npx semantic-release
